### ISSUE TITLE
kitchen user with zsh shell breaks ssh connection

### ISSUE THREAD

**Issue by EugenMayer** [neillturner/kitchen-ansible#308] opened 2019-07-02 10:25 UTC
I am running kitchen ansible tests against my docker image - works fairly fine and it has gone pretty far already.

After quiet some tests and tasks, i know configured the "ansible user", which is kitchen in my case, to use zsh. As soon as this happens, `converge` is no longer working.

Interestingly i can still `loging` using kitchen, ssh is up an running in general.

By simply installing zsh and changing the default shell in /etc/passwd manually, i already can reproduce this. I attached the logs below for insight ().

If i change the default shell back to `/bin/bash` - converge works again ( the actual preboot of converge i guess )

```
       Transferring files to <common-manjaro>
D      TIMING: scp async upload (Kitchen::Transport::Ssh)
D      TIMING: scp async upload (Kitchen::Transport::Ssh) took (0m1.25s)
D      Transfer complete
D      *** COMMAND TO RUN:
D      if [ $(uname -s) == 'FreeBSD' ]; then ETC_ANSIBLE='/usr/local/etc/ansible'; else ETC_ANSIBLE='/etc/ansible'; fi && sudo -E bash -c "[ -d $ETC_ANSIBLE ] || mkdir $ETC_ANSIBLE" && sudo -E cp /tmp/kitchen/ansible.cfg $ETC_ANSIBLE/. && sudo -E cp -r /tmp/kitchen/group_vars $ETC_ANSIBLE/. && sudo -E cp -r /tmp/kitchen/host_vars $ETC_ANSIBLE/. && ansible-galaxy install --force  -p /tmp/kitchen/roles -r /tmp/kitchen/requirements.yml
D      [SSH] kitchen@localhost<{:user_known_hosts_file=>"/dev/null", :port=>32852, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/em/kontextwork/macos-ansible/.kitchen/docker_id_rsa"], :auth_methods=>["publickey"], :forward_agent=>true, :verify_host_key=>:never, :logger=>#<Logger:0x00007fa05826df40 @level=4, @progname=nil, @default_formatter=#<Logger::Formatter:0x00007fa05826def0 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00007fa05826dea0 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00007fa05826de50>>>, :password_prompt=>#<Net::SSH::Prompt:0x00007fa05826de28>, :user=>"kitchen"}> (if [ $(uname -s) == 'FreeBSD' ]; then ETC_ANSIBLE='/usr/local/etc/ansible'; else ETC_ANSIBLE='/etc/ansible'; fi && sudo -E bash -c "[ -d $ETC_ANSIBLE ] || mkdir $ETC_ANSIBLE" && sudo -E cp /tmp/kitchen/ansible.cfg $ETC_ANSIBLE/. && sudo -E cp -r /tmp/kitchen/group_vars $ETC_ANSIBLE/. && sudo -E cp -r /tmp/kitchen/host_vars $ETC_ANSIBLE/. && ansible-galaxy install --force  -p /tmp/kitchen/roles -r /tmp/kitchen/requirements.yml)
      zsh:1: = not found
D      Cleaning up local sandbox in /var/folders/dl/sr5xck0x3nz79wdqvstg1tb00000gn/T/common-manjaro-sandbox-20190702-2295-cv9tcd
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <common-manjaro>.  Please see .kitchen/logs/common-manjaro.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Converge failed on instance <common-manjaro>.  Please see .kitchen/logs/common-manjaro.log for more details
D      ----------------------
D      ------Backtrace-------
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:183:in `report_errors'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:174:in `run_action'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/command/action.rb:36:in `block in call'
D      /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/command/action.rb:34:in `call'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/cli.rb:52:in `perform'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/bin/kitchen:13:in `block in <top (required)>'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/bin/kitchen:13:in `<top (required)>'
D      /Users/em/.chefdk/gem/ruby/2.5.0/bin/kitchen:23:in `load'
D      /Users/em/.chefdk/gem/ruby/2.5.0/bin/kitchen:23:in `<top (required)>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
D      /opt/chefdk/embedded/bin/bundle:23:in `load'
D      /opt/chefdk/embedded/bin/bundle:23:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::InstanceFailure
D      Message: Converge failed on instance <common-manjaro>.  Please see .kitchen/logs/common-manjaro.log for more details
D      ----------------------
D      ------Backtrace-------
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/provisioner/base.rb:95:in `rescue in call'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/provisioner/base.rb:71:in `call'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:409:in `block in converge_action'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:552:in `synchronize_or_call'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:514:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:513:in `action'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:404:in `converge_action'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:381:in `block in transition_to'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:380:in `each'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:380:in `transition_to'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:140:in `converge'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:197:in `public_send'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SSH exited (1) for command: [if [ $(uname -s) == 'FreeBSD' ]; then ETC_ANSIBLE='/usr/local/etc/ansible'; else ETC_ANSIBLE='/etc/ansible'; fi && sudo -E bash -c "[ -d $ETC_ANSIBLE ] || mkdir $ETC_ANSIBLE" && sudo -E cp /tmp/kitchen/ansible.cfg $ETC_ANSIBLE/. && sudo -E cp -r /tmp/kitchen/group_vars $ETC_ANSIBLE/. && sudo -E cp -r /tmp/kitchen/host_vars $ETC_ANSIBLE/. && ansible-galaxy install --force  -p /tmp/kitchen/roles -r /tmp/kitchen/requirements.yml]
D      ----------------------
D      ------Backtrace-------
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/provisioner/base.rb:95:in `rescue in call'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/provisioner/base.rb:71:in `call'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:409:in `block in converge_action'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:552:in `synchronize_or_call'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:514:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:513:in `action'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:404:in `converge_action'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:381:in `block in transition_to'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:380:in `each'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:380:in `transition_to'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:140:in `converge'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:197:in `public_send'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /Users/em/.chefdk/gem/ruby/2.5.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
```

that "zsh:1 not found" might be the actual reason, i could imagine shell expression is not compatible with the zsh syntax at one point"

**Comment by neillturner** [comment] 2019-07-23 09:50
only tested with bash. not going to test with zsh so closing.

**Closed by neillturner** 2019-07-23 09:50 UTC

**Comment by notnmeyer** [comment] 2019-12-12 16:28
the default shell on macos catalina is zsh. so this is broken out of the box for catalina vms unless the default shell is changed to bash. i'll try and take a look in a bit and see if i can get this working with zsh.

**Comment by DWSR** [comment] 2020-11-05 20:51
@EugenMayer @notnmeyer I've opened a PR that will make this provisioner work under ZSH. The cause of the incompatibility was a Bashism in the commands run by the provisioner: `==` is not valid in `[ ... ]`, but is valid in `[[ ... ]]`. The side effect is that this _should_ make the provisioner work on any POSIX-compatible shell (like Busybox).
