### ISSUE TITLE
When using callback_plugins, subsequent converges fail due to wrong permissions.

### ISSUE THREAD

**Issue by marcoamorales** [neillturner/kitchen-ansible#134] opened 2016-02-11 20:53 UTC
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [scp: /tmp/kitchen/callback_plugins/profile_tasks.pyc: Permission denied
]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

the `*.pyc` file is owned by root:

```
root@ip-172-32-15-212:~# ll /tmp/kitchen/callback_plugins/
total 16
drwxr-xr-x 2 ubuntu ubuntu 4096 Feb 11 20:29 ./
drwxrwxr-x 7 ubuntu ubuntu 4096 Feb 11 20:48 ../
-rw-r--r-- 1 ubuntu ubuntu 1854 Feb 11 20:48 profile_tasks.py
-rw-r--r-- 1 root   root   2100 Feb 11 20:29 profile_tasks.pyc
```

**Comment by neillturner** [comment] 2016-02-12 19:11
Well the provisioner code does not do anything with permissions. 
 basically it copies them to a sandbox on you workstation 
 and then the driver uploads them from your workstation sandbox to the remote machine.
if to run with  -l debug on your command you will see when the sandbox is on you machine and you can  have a look at the permissions. 
 I guess it depends on what your workstation is windows, mac or linux and what driver you are using that does the upload.

**Comment by neillturner** [comment] 2016-03-19 14:05
Any more details n this. My guess is that test kitchen is running as root or sudo when it copies this file and it is being created with root. Maybe you had a previous run where you ran as ubuntu instead of root and that how the files got different owners. 
 I would test again by deleting the /tmp/kitchen directory and running again to see if all the files get the same owners.  test-kitchen just runs as one particular users so should not get situation where files are different owners.

**Comment by neillturner** [comment] 2016-03-19 14:06
i'll leave open for a couple more weeks and then close.

**Comment by rafe-delphix** [comment] 2016-05-06 20:44
I'm experiencing a similar issue.  I do not believe I ran any deployments as root.  The pyc files exist on my local machine, but they are owned by my local user.  They presume they are copied over, and there is no issue the first time I run converge.  However, the second time I run converge the pyc files cannot be deleted because they are owned by root.

It looks like something happens after they are copied, such as a python pre-compilation step.  This may not be something that is done by kitchen-ansible, but something that is done by ansible itself.  I suspect this is the case because in another role, I began to have difficulty deploying that python plugin when the python itself had an error, even though the role I was deploying did not use it.

I'm going to look further in to it.

**Comment by rafe-delphix** [comment] 2016-05-06 21:00
I think what's happening is that the plugin directories are always built and used by ansible itself.  If you run a normal ansible deployment it will run locally and compile them as the running user.  When the provisioner runs it copies everything in those directories including the pyc files.  When ansible runs on the remote server, it must compile the plugins as root.  This overrides the pyc files.

WORKAROUND: Delete all the pyc files from your local plugin directories after running ansible outside of kitchen.  Then you do not need to delete the pyc from the remote /tmp/kitchen directory every time.

I have a question?  It seems that ansible normally runs as the authenticated user when run normally.  Why does kitchen-ansible run ansible as root?

**Comment by neillturner** [comment] 2016-05-07 08:06
well chef and puppet run as root because they install packages etc that need root access so the kitchen-ansible runs as root as well. 
there is a parameter ansible_sudo  that defaults to true, if you set this to false then it will not add the sudo command and so run as authenticated user. 

should  the provisioner change all the files in  callback_plugins  that have suffixes py and pyc to 
chmod 777  and change the owner of the files to the owner of the plugins directory owner to fix this issue?   
or should i not be copying the plugins directory because ansible is building it?

**Comment by rafe-delphix** [comment] 2016-05-09 19:18
Given that the strategy of the kitchen-ansible test harness is to copy the target directory from to the test target and run Ansible from there, I'm uncertain how I would approach this problem.  This is not a bug of kitchen-ansible, since it's following a logical course of action.

I would think you need to copy over the plugin directory as those plugins might be necessary for the completion of the ansible target under test.  One option is that you don't copy pyc from the callback directory, however, I can envision a (likely theoretical) scenario where one is running plugins from binary, as in the user doesn't have access to pyc files.  This would cause another unexpected result where those python classes are mysteriously not found because they are never copied.

You might just approach this as more of an experience issue.  In this case, maybe if there is some way to detect the case and provide a more detailed error message for users that might explain the scenario.

Please forgive me, although I'm an experienced developer I'm new to devops and ansible, so DO point out where my mistakes are, and accept the following as a walkthrough of my reasoning.  I should have checked about how ansible normally runs, and the default setting is in fact to run as root, so it's obvious why kitchen-ansible does it.

**Comment by neillturner** [comment] 2016-05-10 07:49
you can run ansible in ssh mode instead of local mode and then it can be used to configure and test a remote server. 
```
+------------------+              +------------------------+               +----------------------+
| Workstation      |              |  TK installs ansible|               |    Your server for  |
|                         |              |  and copies repo    |              |    configuring and  |
|    +-------+        |              |       +---------+         |    ssh     |    testing remotely |
|    |Test   +-------------------->     |   Ansible---------------------->                         |
|    |Kitchen|       |              |       |             |         |               |                              |
|    +-------+        |              |       +---------+         |               |                              |
|                         |              |                               |               |                              |
+------------------+              +------------------------+               +----------------------+
```

**Comment by rafe-delphix** [comment] 2016-05-13 20:33
I'm beginning to understand more how ansible and kitchen and kitchen-ansible are meant to work together.  I think that this multi-host thing you describe is what we ought to be doing.  I wasn't sure how to support multiple hosts but I think I get it.  I can define multiple hosts inside my kitchen-ansible test playbook, send ansible to the "push" host, and the role will get sent to the target host via SSH.  I think I need to do it this way because I've defined a role that installs ansible itself, and the kitchen-ansible installation of ansible was getting in the way (sorry for all that 'ansible').

I'll file a feature request if you think it makes sense and there is no currently a way to do it, but instead of copying the files from the workstation to the ansible target machine, how about just providing mounts for when using vagrant and docker on localhost?

**Comment by neillturner** [comment] 2016-05-14 07:40
there is another plugin out there for ansibe called ansiblepush which drives everything from your workstation, this might be what you are looking for.

**Comment by rafe-delphix** [comment] 2016-05-14 22:26
I know about that provisioner.  Given what I've been learning about regarding kitchen, I'm uncertain that it provides the best solution either because:
  * From what I can tell, kitchen-ansible is more mature than kitchen-ansiblepush.
  * kitchen-ansible may be closer to how kitchen expects provisioners to behave, for example I realize now that the file copying operation is directed by kitchen, not kitchen-ansible.  How does that operation make sense when you are using ansible to push from you local host?  What does kitchen-ansiblepush do about the Kitchen copy operation?

It's been tricky for me to understand how kitchen is actually supposed to work, I think because there is such scarce documentation.  I also think it's mainly developed with Chef (master-slave) in mind which means Ansible has difficulty fitting in perfectly.  Such is life!

The next thing that gives me pause about attempting a multi-machine kitchen test setup is I don't know how busser runs the verification stuff.  It sounds like it wants to run on the 'prepared instance', which means they run on the remote server.  I could try it but I'm not sure if it would run correctly via kitchen-ansible using the ssh connection.  Do you know about how/where busser runs?

I've also found reasonable evidence that kitchen is not meant to test against clusters (https://github.com/test-kitchen/test-kitchen/issues/184).  That said, maybe supporting a 2 machine set up could be a good addition to kitchen-ansible so that it effectively works the same was as kitchen-ansiblepush, but theoretically cleaner.  I may experiment with that idea, unless you already know why it's a bad idea.

Ultimately, I think we are going to stick with kitchen-ansible.

**Comment by neillturner** [comment] 2016-05-15 12:32
actually its designed to work with chef-solo which is designed to run on the same server that you are configuring. That's why they say kitchen is not meant to test against clusters (test-kitchen/test-kitchen#184) 
I would go with my kitchen-verifier-serverspec plugin. then you don't need all that busser stuff. 
I would set the require_chef_for_busser to false and just get the ansible provisioning working. 
then i would add my https://github.com/neillturner/kitchen-verifier-serverspec to do the tests. 
also you can see sample ansible repos at 
https://github.com/neillturner/ansible_repo
and 
and an example kitchen yaml file at: 
https://github.com/neillturner/ansible_repo/blob/master/.kitchen.yml.ssh_ssh
even windows support at: 

https://github.com/neillturner/ansible_windows_repo

noye

**Comment by neillturner** [comment] 2016-08-04 08:51
closing

**Closed by neillturner** 2016-08-04 08:51 UTC
