### ISSUE TITLE
kitchen converge stack traces under RHEL family 

### ISSUE THREAD

**Issue by darkn3rd** [neillturner/kitchen-ansible#288] opened 2018-09-05 16:27 UTC
When you converge a system twice, it will stack trace.

### ENVIRONMENT

* Host: `Mac OS X 10.13.5`
* Guest `CentOS Linux 7` (from `bento/centos-7` box)
* ChefDK `3.1.0`
* Test Kitchen `1.22.0`
* kitchen-vagrant `1.3.2`
* kitchen-ansible `0.48.6`
* Vagrant `2.1.2`
* Virtualbox `5.2.16r123759`

### STEPS

Minimal steps I used to reproduce the issue.

```bash
PROVISION_PATH=~/vagrant-ansible/provisioning
ROLE_PATH=${PROVISION_PATH}/roles/hello_web

mkdir -p ${ROLE_PATH}/{defaults,files,tasks}
touch ${ROLE_PATH}/{defaults,tasks}/main.yml \
  ${PROVISION_PATH}/playbook.yml ${ROLE_PATH}/files/index.html

cat <<-'KITCHENCFG' > ${ROLE_PATH}/.kitchen.yml
---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: true
  require_ansible_omnibus: false
  ansible_verbose: true
  ansible_diff: true
  roles_path: ../../roles
  playbook: ../../playbook.yml

platforms:
  - name: centos-7

suites:
  - name: default
KITCHENCFG

cat <<-'PLAYBOOK' > ${PROVISION_PATH}/playbook.yml
---
- hosts: all
  gather_facts: yes
  become: true
PLAYBOOK

cd ${ROLE_PATH}


kitchen create
kitchen configure
kitchen configure
```

### DEBUG

Using: `kitchen converge -l debug`

https://gist.github.com/darkn3rd/712d073a4cd439c429a25619ab0bf03b

### EXPECTED RESULTS

I would be able to run a playbook without stack tracking.  Toward end of convergence phase, there's a sync process, which should not stack trace.

### ACTUAL RESULTS

Toward end of convergence phase, there's a sync process, which should not stack trace.  This does not happen on Ubuntu

```log
I, [2018-09-05T09:13:45.909618 #35821]  INFO -- default-centos-7: -----> Converging <default-centos-7>...
I, [2018-09-05T09:13:45.910172 #35821]  INFO -- default-centos-7: Preparing files for transfer
I, [2018-09-05T09:13:45.910285 #35821]  INFO -- default-centos-7: Preparing playbook
I, [2018-09-05T09:13:45.911632 #35821]  INFO -- default-centos-7: Preparing inventory
I, [2018-09-05T09:13:45.911716 #35821]  INFO -- default-centos-7: Preparing modules
I, [2018-09-05T09:13:45.911909 #35821]  INFO -- default-centos-7: nothing to do for modules
I, [2018-09-05T09:13:45.911964 #35821]  INFO -- default-centos-7: Preparing roles
I, [2018-09-05T09:13:45.918813 #35821]  INFO -- default-centos-7: Preparing ansible.cfg file
I, [2018-09-05T09:13:45.918948 #35821]  INFO -- default-centos-7: Empty ansible.cfg generated
I, [2018-09-05T09:13:45.919195 #35821]  INFO -- default-centos-7: Preparing group_vars
I, [2018-09-05T09:13:45.919414 #35821]  INFO -- default-centos-7: nothing to do for group_vars
I, [2018-09-05T09:13:45.919468 #35821]  INFO -- default-centos-7: Preparing additional_copy_path
I, [2018-09-05T09:13:45.919702 #35821]  INFO -- default-centos-7: Preparing host_vars
I, [2018-09-05T09:13:45.919890 #35821]  INFO -- default-centos-7: nothing to do for host_vars
I, [2018-09-05T09:13:45.919951 #35821]  INFO -- default-centos-7: Preparing hosts file
I, [2018-09-05T09:13:45.920206 #35821]  INFO -- default-centos-7: Preparing spec
I, [2018-09-05T09:13:45.920418 #35821]  INFO -- default-centos-7: nothing to do for spec
I, [2018-09-05T09:13:45.920492 #35821]  INFO -- default-centos-7: Preparing library plugins
I, [2018-09-05T09:13:45.920785 #35821]  INFO -- default-centos-7: nothing to do for library plugins
I, [2018-09-05T09:13:45.920836 #35821]  INFO -- default-centos-7: Preparing callback plugins
I, [2018-09-05T09:13:45.921053 #35821]  INFO -- default-centos-7: nothing to do for callback plugins
I, [2018-09-05T09:13:45.921101 #35821]  INFO -- default-centos-7: Preparing filter_plugins
I, [2018-09-05T09:13:45.921355 #35821]  INFO -- default-centos-7: nothing to do for filter_plugins
I, [2018-09-05T09:13:45.921408 #35821]  INFO -- default-centos-7: Preparing lookup_plugins
I, [2018-09-05T09:13:45.921670 #35821]  INFO -- default-centos-7: nothing to do for lookup_plugins
I, [2018-09-05T09:13:45.921769 #35821]  INFO -- default-centos-7: Preparing ansible vault password
I, [2018-09-05T09:13:45.921994 #35821]  INFO -- default-centos-7: Preparing additional_ssh_private_keys
I, [2018-09-05T09:13:45.922105 #35821]  INFO -- default-centos-7: nothing to do for additional_ssh_private_keys
I, [2018-09-05T09:13:45.922155 #35821]  INFO -- default-centos-7: Finished Preparing files for transfer
I, [2018-09-05T09:13:45.922431 #35821]  INFO -- default-centos-7: Installing ansible, will try to determine platform os
I, [2018-09-05T09:13:46.233531 #35821]  INFO -- default-centos-7: Transferring files to <default-centos-7>
E, [2018-09-05T09:13:46.322573 #35821] ERROR -- default-centos-7: Converge failed on instance <default-centos-7>.
E, [2018-09-05T09:13:46.322714 #35821] ERROR -- default-centos-7: ------Exception-------
E, [2018-09-05T09:13:46.322747 #35821] ERROR -- default-centos-7: Class: Kitchen::ActionFailed
E, [2018-09-05T09:13:46.322768 #35821] ERROR -- default-centos-7: Message: SCP upload failed (open failed (1))
E, [2018-09-05T09:13:46.322787 #35821] ERROR -- default-centos-7: ----------------------
E, [2018-09-05T09:13:46.322805 #35821] ERROR -- default-centos-7: ------Backtrace-------
E, [2018-09-05T09:13:46.322822 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/provisioner/base.rb:91:in `rescue in call'
E, [2018-09-05T09:13:46.322840 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/provisioner/base.rb:67:in `call'
E, [2018-09-05T09:13:46.322858 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:393:in `block in converge_action'
E, [2018-09-05T09:13:46.322876 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:536:in `synchronize_or_call'
E, [2018-09-05T09:13:46.322913 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:498:in `block in action'
E, [2018-09-05T09:13:46.322944 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2018-09-05T09:13:46.322962 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:497:in `action'
E, [2018-09-05T09:13:46.322980 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:389:in `converge_action'
E, [2018-09-05T09:13:46.322997 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:368:in `block in transition_to'
E, [2018-09-05T09:13:46.323014 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:367:in `each'
E, [2018-09-05T09:13:46.323032 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:367:in `transition_to'
E, [2018-09-05T09:13:46.323050 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:135:in `converge'
E, [2018-09-05T09:13:46.323067 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:197:in `public_send'
E, [2018-09-05T09:13:46.323084 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-09-05T09:13:46.323101 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-09-05T09:13:46.323119 #35821] ERROR -- default-centos-7: ----End Backtrace-----
E, [2018-09-05T09:13:46.323135 #35821] ERROR -- default-centos-7: ---Nested Exception---
E, [2018-09-05T09:13:46.323152 #35821] ERROR -- default-centos-7: Class: Kitchen::Transport::SshFailed
E, [2018-09-05T09:13:46.323168 #35821] ERROR -- default-centos-7: Message: SCP upload failed (open failed (1))
E, [2018-09-05T09:13:46.323185 #35821] ERROR -- default-centos-7: ----------------------
E, [2018-09-05T09:13:46.323202 #35821] ERROR -- default-centos-7: ------Backtrace-------
E, [2018-09-05T09:13:46.323218 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/provisioner/base.rb:91:in `rescue in call'
E, [2018-09-05T09:13:46.323236 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/provisioner/base.rb:67:in `call'
E, [2018-09-05T09:13:46.323253 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:393:in `block in converge_action'
E, [2018-09-05T09:13:46.323270 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:536:in `synchronize_or_call'
E, [2018-09-05T09:13:46.323287 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:498:in `block in action'
E, [2018-09-05T09:13:46.323305 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2018-09-05T09:13:46.323322 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:497:in `action'
E, [2018-09-05T09:13:46.323339 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:389:in `converge_action'
E, [2018-09-05T09:13:46.323356 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:368:in `block in transition_to'
E, [2018-09-05T09:13:46.323388 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:367:in `each'
E, [2018-09-05T09:13:46.323407 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:367:in `transition_to'
E, [2018-09-05T09:13:46.323425 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:135:in `converge'
E, [2018-09-05T09:13:46.323443 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:197:in `public_send'
E, [2018-09-05T09:13:46.323460 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-09-05T09:13:46.323478 #35821] ERROR -- default-centos-7: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-09-05T09:13:46.323495 #35821] ERROR -- default-centos-7: ----End Backtrace-----
```

**Comment by neillturner** [comment] 2018-09-17 17:03
Can't reproduce on my environment 

windows
ruby 2.4.1p111 (2017-03-22 revision 58053) [i386-mingw32]
vagrant 2.0.1 
kitchen-vagrant 1.2.1 
kitchen-ansible 0.48.6
virtualbox 5.1.26r117224
 
using https://github.com/neillturner/ansible_vagrant_repo
 using bento/centos7

so closing

**Closed by neillturner** 2018-09-17 17:03 UTC
